### ISSUE TITLE
The application crashes on startup, it is impossible to start it.

### ISSUE THREAD

**Issue by Wjxfi** [arturkowalczyk300/android-cryptocurrency-prices#27] opened 2023-06-16 21:28 UTC
I uninstalled the 0.8.4 izzyondroid version. Installed 0.9.2 github version. In the old version there were no crashes, in the new version there are

**Comment by arturkowalczyk300** [comment] 2023-07-05 05:52
Sorry for the inconvenience.  

I have two questions:
1. What device do you have? And what is your Android OS version?
2. Did you run new version of app for the first time with access to stable internet connection or in offline mode? 
I'm asking that because, while ago I observed app stopping updating when first start after app install is made in offline mode. Anyway, it does not crash, just requires restart in online mode.

Bug described in last sentence will be fixed in the new version, but I'm afraid it may not fix your case and I probably need more information.

**Comment by arturkowalczyk300** [comment] 2024-02-25 21:44
After some time, I've managed to reproduce a crash during startup. It was occurring on devices with API level of at least 31. The problem laid in incorrect pending intent configuration. I have fixed it in the latest release: [v0.9.3](https://github.com/arturkowalczyk300/android-cryptocurrency-prices/releases/tag/v0.9.3).

Thank you for reporting the issue and sorry for long time elapsed until fixed.

**Closed by arturkowalczyk300** 2024-02-25 21:44 UTC
